# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arusumauser',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='arusumauser',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
