# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0002_auto_20180818_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='arusumauser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
