# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 18:41
from __future__ import unicode_literals

import arusuma.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0003_arusumauser_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='arusumauser',
            managers=[
                ('objects', arusuma.models.ArusumaUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='arusumauser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='arusumauser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='arusumauser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
