# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0005_auto_20180819_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AceessToken',
            new_name='AccessToken',
        ),
    ]
