# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0006_auto_20180819_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, default='', max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
