# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0008_auto_20180819_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='refresh_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
