# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0009_accesstoken_refresh_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='expired_at',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
