# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arusuma', '0011_auto_20180821_0041'),
        ('arusuma', '0011_auto_20180821_0044'),
    ]

    operations = [
    ]
